# Auto-generated database schema
# Generated by generate_schema.nim

import std/tables
import std/options
import src/shared/schema_parser

const GENERATED_SCHEMA* = block:
  var schema = DatabaseSchema(tables: initTable[string, TableSchema]())
  
  schema.tables["users"] = TableSchema(
    name: "users",
    columns: @[
      ColumnInfo(name: "id", sqliteType: INTEGER, constraints: {ccPrimaryKey}),
      ColumnInfo(name: "name", sqliteType: TEXT, constraints: {ccNotNull}),
    ]
  )

  schema.tables["books"] = TableSchema(
    name: "books",
    columns: @[
      ColumnInfo(name: "id", sqliteType: INTEGER, constraints: {ccPrimaryKey}),
      ColumnInfo(name: "title", sqliteType: TEXT, constraints: {}),
    ]
  )

  schema
