# Auto-generated database schema
# Generated by generate_schema.nim

import std/tables
import std/options
import src/shared/schema_parser

const GENERATED_SCHEMA* = block:
  var schema = DatabaseSchema(tables: initTable[string, TableSchema]())
  
  schema.tables["users"] = TableSchema(
    name: "users",
    columns: @[
      ColumnInfo(name: "id", sqliteType: INTEGER, constraints: {ccPrimaryKey, ccAutoIncrement}),
      ColumnInfo(name: "name", sqliteType: TEXT, constraints: {}),
      ColumnInfo(name: "email", sqliteType: TEXT, constraints: {ccUnique}),
      ColumnInfo(name: "age", sqliteType: INTEGER, constraints: {}),
    ]
  )

  schema.tables["products"] = TableSchema(
    name: "products",
    columns: @[
      ColumnInfo(name: "id", sqliteType: INTEGER, constraints: {ccPrimaryKey, ccAutoIncrement}),
      ColumnInfo(name: "name", sqliteType: TEXT, constraints: {}),
      ColumnInfo(name: "description", sqliteType: TEXT, constraints: {}),
      ColumnInfo(name: "price", sqliteType: INTEGER, constraints: {}),
      ColumnInfo(name: "stock", sqliteType: INTEGER, constraints: {}),
    ]
  )

  schema
