name: build
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    

jobs:
  build:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install choosenim
        run: curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y

      - name: export env
        run:  export PATH=/home/runner/.nimble/bin:$PATH
      
      - name: echo nim version
        run:  nim -v
