name: build
on:
  push:
    branches:
      - main
    

jobs:
  build:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install choosenim
        run: curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y

      - name: set path
        run:  echo ~/.nimble/bin >> $GITHUB_PATH

      - name: echo nim version
        run:  nim -v
    
      - uses: actions/cache@v4
        id: cache-nimble
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: build
        run: nimble build
 